[staging]
staging-node ansible_host=localhost ansible_connection=local env_name=staging app_port=8082 deploy_dir=/tmp/myapp_staging

[production]
prod-node ansible_host=localhost ansible_connection=local env_name=production app_port=8083 deploy_dir=/tmp/myapp_production