pipeline {
    agent any
    
    tools {
        maven 'Maven3' 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                echo 'Compiling the Java application...'
                sh 'mvn clean compile'
            }
        }
        
        stage('Unit Test') {
            steps {
                echo 'Running JUnit tests...'
                sh 'mvn test'
            }
        }
    }
}