pipeline {
	agent any

	stages {
	    stage('Test') {
		steps {
		    echo 'Hello from my first pipeiline'
		    echo 'So this is to test the change happend here'
		    echo 'Automated Build using webhook and ngrok successful'
		}
	    }
	}
}
